---
depends:
  - "Test02"
files:
  - js/main.js
asking:
  what 2 say:
    singleton: Greetings
  who should listen:
    new: Every
  #Class03:
  #  instance_by_arg: Test03
  who:
    string: "World"
  
