---
depends:
  - "Test02"
files:
  - js/main.js
asking:
  what 2 say:
    singleton: Greetings
  who should listen:
    new: Every
    constructor:
      - string: "log"
    setter:
      do_log:
        bool: false
  who:
    string: "World"
  
