---
depends:
  - "Test02"
files:
  - js/main.js
asking:
  false:
    bool: false
  what 2 say:
    singleton: Greetings
  who should listen:
    new: Every
    constructor:
      - string: "log"
    setter:
      do_log: false
  who:
    string: '{"W" + "o" + ["r","l","d"].join("")}'
  
